# Generated by Django 3.1.3 on 2020-11-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('username_info', models.TextField()),
                ('repos_info', models.TextField()),
            ],
        ),
    ]
